logging:
  level: INFO
  debug: "spacemake.util.read_fq"

puck_data:
    barcode_file: 'predictions_ml.csv'
    root: 'puck_data'

pucks:
    default:
        width_um: 3000
        spot_diameter_um: 10
    visium:
        barcodes: 'puck_data/visium_barcode_positions.csv'
        width_um: 6500
        spot_diameter_um: 55
    seq_scope:
        width_um: 1000
        spot_diameter_um: 1
    slide_seq:
        width_um: 3000
        spot_diameter_um: 10

run_modes:
    default:
        n_beads: 100000
        umi_cutoff: [100, 300, 500]
        clean_dge: False
        detect_tissue: False
        polyA_adapter_trimming: True
        count_intronic_reads: True
        count_mm_reads: False
        mesh_data: False
        mesh_type: 'circle'
        mesh_spot_diameter_um: 55
        mesh_spot_distance_um: 100
    visium:
        n_beads: 10000
        umi_cutoff: [1000]
        clean_dge: False
        detect_tissue: True
        count_intronic_reads: False
        count_mm_reads: True
    slide_seq:
        n_beads: 100000
        umi_cutoff: [50]
        clean_dge: False
        detect_tissue: False
    scRNA_seq:
        n_beads: 10000
        umi_cutoff: [500]
        detect_tissue: False
        count_intronic_reads: True
        count_mm_reads: False
    seq_scope:
        clean_dge: false
        count_intronic_reads: false
        count_mm_reads: false
        detect_tissue: false
        mesh_data: true
        mesh_spot_diameter_um: 10
        mesh_spot_distance_um: 15
        mesh_type: hexagon
        n_beads: 1000
        umi_cutoff:
        - 100
        - 300

barcode_flavors:
    default:
        cell: "r1[0:12]"
        UMI: "r1[12:20]"
    dropseq:
        cell: "r1[0:12]"
        UMI: "r1[12:20]"
    slide_seq_14bc:
        cell: "r1[0:14]"
        UMI: "r1[14:23]"
    slide_seq_15bc:
        cell: "r1[0:14]"
        UMI: "r1[15:23]"
    visium:
        cell: "r1[0:16]"
        UMI: "r1[16:28]"
    sc_10x_v2:
        cell: "r1[0:16]"
        UMI: "r1[16:26]"
        min_qual_trim: 30
    sc_10x_v3:
        cell: r1[0:16]
        UMI: r1[16:28]
        min_qual_trim: 30
    seq_scope:
        UMI: "r2[0:9]"
        cell: "r1[0:20]"
    nextflex:
        min_qual_trim: 20
        cell: "'A'"
        read1: "None"
        UMI: "r2[:4] + r2[-4:]"
        seq: "r2[4:-4]"
        qual: "r2_qual[4:-4]"

adapters:
  optical_primer: GAATCACGATACGTACACCA
  TSO_SMART: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  SMART: AAGCAGTGGTATCAACGCAGAGTG
  TSO_10x: AAGCAGTGGTATCAACGCAGAGTACATGGG
  chromium_bead: CTACACGACGCTCTTCCGATCT
  dropseq_bead: AAGCAGTGGTATCAACGCAGAGTAC
  polyA: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  polyG: GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
  nextflex_RA3: TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTGAA
  truseq_RA3: TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCGTCCA

adapter_flavors:
  SMARTER:
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_error: 0.25
        min_overlap: 3
    paired_end: replace_N
  chromium:
    cut_right:
    - Q:
        min_base_quality: 32
    - polyA:
        max_error: 0.25
        min_overlap: 3
    - polyG:
        max_error: 0.1
        min_overlap: 3
  dropseq:
    cut_left:
    - TSO_SMART:
        max_error: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_error: 0.25
        min_overlap: 3
    - polyG:
        max_error: 0.1
        min_overlap: 3
    paired_end: single-end
  default:
    cut_left:
    - TSO_SMART:
          max_error: 0.1
          min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_error: 0.25
        min_overlap: 3
    - polyG:
        max_error: 0.1
        min_overlap: 3
    paired_end: single-end
  dropseq:
    cut_left:
    - TSO_SMART:
        max_errors: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_errors: 0.25
        min_overlap: 3
    - polyG:
        max_errors: 0.1
        min_overlap: 3
    paired_end: single-end
  fc_SMART_UMI_RPE:
    cut_left:
    - TSO_SMART:
        max_errors: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 32
    - polyG:
        max_errors: 0.25
        min_overlap: 3
    - Q:
        min_base_quality: 32
    - polyA:
        max_errors: 0.25
        min_overlap: 3
  slac_10x:
    cut_left:
    - TSO_10x:
        max_errors: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 32
    - polyG:
        max_errors: 0.2
        min_overlap: 3
    - polyA:
        max_errors: 0.25
        min_overlap: 3
  truseq:
    cut_right:
    - Q:
        min_base_quality: 29
    - polyG:
        max_errors: 0.2
        min_overlap: 3
    - truseq_RA3:
        max_errors: 0.2
        min_overlap: 3        
quant:
  default:
    counter_class: "spacemake.quant.mRNACounter"
    channels: 
      - "counts"
      - "reads"
      - "exonic_counts"
      - "exonic_reads"
      - "intronic_counts"
      - "intronic_reads"
    X_counts: ["exonic_counts", "intronic_counts"]
    X_reads: ["exonic_reads", "intronic_reads"]
    alignment_priorities: {
        'C': 100, # coding exon
        'U': 100, # UTR exon
        'N': 90, # exon of non-coding transcript
        'I': 50, # intronic region
        # lower case == antisense
        'c': 10,
        'u': 10,
        'n': 9,
        'i': 5,
        # intergenic
        '-': 0,
    }
    gene_priorities: {
        'C': 100, # coding exon
        'U': 100, # UTR exon
        'N': 90, # exon of non-coding transcript
        'I': 50, # intronic region
        'c': 10,
        'u': 10,
        'n': 9,
        'i': 5,
        '-': 0,
    }
    exonic_tags: ["C", "U", "N"]
    intronic_tags: ["I", "i"]
  custom_index:
    counter_class: "spacemake.quant.CustomIndexCounter"
    channels: 
      - "counts"
      - "reads"
#      - "exonic_counts"
#      - "exonic_reads"
