barcode_flavors:
    default:
        cell: "r1[0:12]"
        UMI: "r1[12:20]"
    dropseq:
        cell: "r1[0:12]"
        UMI: "r1[12:20]"
    slide_seq_14bc:
        cell: "r1[0:14]"
        UMI: "r1[14:23]"
    slide_seq_15bc:
        cell: "r1[0:14]"
        UMI: "r1[15:23]"
    visium:
        cell: "r1[0:16]"
        UMI: "r1[16:28]"
    sc_10x_v2:
        cell: "r1[0:16]"
        UMI: "r1[16:26]"
        min_qual_trim: 30
    sc_10x_v3:
        cell: r1[0:16]
        UMI: r1[16:28]
        min_qual_trim: 30
    seq_scope:
        UMI: "r2[0:9]"
        cell: "r1[0:20]"
    nextflex:
        min_qual_trim: 20
        cell: "'A'"
        read1: "None"
        UMI: "r2[:4] + r2[-4:]"
        seq: "r2[4:-4]"
        qual: "r2_qual[4:-4]"

adapters:
  optical_primer: GAATCACGATACGTACACCA
  TSO_SMART: AAGCAGTGGTATCAACGCAGAGTGAATGGG
  SMART: AAGCAGTGGTATCAACGCAGAGTG
  TSO_10x: AAGCAGTGGTATCAACGCAGAGTACATGGG
  chromium_bead: CTACACGACGCTCTTCCGATCT
  dropseq_bead: AAGCAGTGGTATCAACGCAGAGTAC
  polyA: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  polyG: GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
  nextflex_RA3: TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTGAA
  truseq_RA3: TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCGTCCA

adapter_flavors:
  default:
    cut_left:
    - TSO_SMART:
          max_error: 0.1
          min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 30
    - polyG:
        max_error: 0.1
        min_overlap: 3
    - polyA:
        max_error: 0.25
        min_overlap: 3
    paired_end: single-end
  SMARTER:
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_error: 0.25
        min_overlap: 3
    paired_end: replace_N
  chromium:
    cut_right:
    - Q:
        min_base_quality: 32
    - polyA:
        max_error: 0.25
        min_overlap: 3
    - polyG:
        max_error: 0.1
        min_overlap: 3
  dropseq:
    cut_left:
    - TSO_SMART:
        max_error: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 30
    - polyA:
        max_error: 0.25
        min_overlap: 3
    - polyG:
        max_error: 0.1
        min_overlap: 3
    paired_end: single-end
  fc_SMART_UMI_RPE:
    cut_left:
    - TSO_SMART:
        max_errors: 0.1
        min_overlap: 10
    cut_right:
    - Q:
        min_base_quality: 32
    - polyG:
        max_errors: 0.25
        min_overlap: 3
    - Q:
        min_base_quality: 32
    - polyA:
        max_errors: 0.25
        min_overlap: 3
  truseq:
    cut_right:
    - Q:
        min_base_quality: 29
    - polyG:
        max_errors: 0.2
        min_overlap: 3
    - truseq_RA3:
        max_errors: 0.2
        min_overlap: 3        

quant:
  default:
    counter_class: "scbamtools.quant.mRNACounter"
    channels: 
      - "counts"
      - "reads"
      - "exonic_counts"
      - "exonic_reads"
      - "intronic_counts"
      - "intronic_reads"
    X_counts: ["exonic_counts", "intronic_counts"]
    X_reads: ["exonic_reads", "intronic_reads"]
    alignment_priorities: {
        'C': 100, # coding exon
        'U': 100, # UTR exon
        'N': 90, # exon of non-coding transcript
        'I': 50, # intronic region
        # lower case == antisense
        'c': 10,
        'u': 10,
        'n': 9,
        'i': 5,
        # intergenic
        '-': 0,
    }
    gene_priorities: {
        'C': 100, # coding exon
        'U': 100, # UTR exon
        'N': 90, # exon of non-coding transcript
        'I': 50, # intronic region
        'c': 10,
        'u': 10,
        'n': 9,
        'i': 5,
        '-': 0,
    }
    exonic_tags: ["C", "U", "N"]
    intronic_tags: ["I", "i"]

  custom_index:
    counter_class: "scbamtools.quant.CustomIndexCounter"
    channels: 
      - "counts"
      - "reads"
#      - "exonic_counts"
#      - "exonic_reads"
